#pragma once
#include <codecvt>
#include <cstdlib>
#include <cstdlib>
#include <filesystem>
#include <fileSystem>
#include <iostream>
#include <locale>
#include <QCoreApplication>
#include <QDataStream>
#include <QDebug>
#include <QFileDialog>
#include <QFocusEvent>
#include <QFontDatabase>
#include <QGraphicsDropShadowEffect>
#include <QMessageBox>
#include <QMouseEvent>
#include <QObject>
#include <QPainter>
#include <QProcess>
#include <QPropertyAnimation>
#include <QStackedWidget>
#include <QStandardPaths>
#include <QString>
#include <QThread>
#include <QTimer>
#include <QWidget>
#include <ShObjIdl.h>
#include <Windows.h>